#!/bin/bash
# first run ./build to build the Plex Docker container
# then configure Plex by editing ./conf (this file) - see README.md for help
# then run ./start to start Plex
# run ./stop to stop Plex

# see README.md before changing settings below

plex_dir="$(pwd)/database"
media="$plex_dir/media"
database="$plex_dir/database"
transcode="$plex_dir/transcode"

port=32400
mode="host" # "host" or "bridged" or "http-only"
servername="Plex Server"
containername="plex"

plexlogin=true
slideshow_speed_ms="default"
tz="America/New_York"
uid="$(id -u)"
gid="$(id -g)"

hostip=""   # normally leave blank
docker_network="172.16.0.0/16,172.17.0.0/16"
image="plexinc/pms-docker:public"

if [ -f "./myconf" ]
then
  source ./myconf
fi
