#!/bin/bash
# Configure Plex by editing ./conf (this file) - see README.md for help
# then run ./start to start Plex
# run ./stop to stop Plex

# see README.md before changing settings below

# configure media directories, using full path names
# rename these if you need to match a current Plex setup
# See README.md for more info
media_folders=(media media1 media2 media3)
media=""
media1=""
media2=""
media3=""

# if you already have a Plex media database, enter the full path name here
# default is "database/config" under the current working directory
config="$(pwd)/database/config"
# default location for transcoded files
transcode="$(pwd)/database/transcode"

servername="Plex Server"
containername="plex"
port=32400
# "host" or "bridged" or "http-only"
mode="host"

plexlogin=true
slideshow_speed_ms="default"
tz="America/New_York"

uid="$(id -u)"
gid="$(id -g)"

# normally leave blank.
# if Plex is running in a VM, set hostip here and ensure that $port is forwarded from the host to the VM
hostip=""
docker_network="172.16.0.0/12"
image="plexinc/pms-docker:public"
restart_policy="always"

#hardware_transcoding_device="/dev/dri:/dev/dri"
hardware_transcoding_device=""

plex_claim_token=""

if [ -f "./myconf" ]
then
  source ./myconf
fi
