#!/bin/bash
# First configure Plex by editing ./conf
# then run ./start to start Plex
# run ./stop to stop Plex (this file)

source ./conf

echo "removing $containername container"
docker container stop $containername >/dev/null
docker container rm $containername >/dev/null
echo "run ./start to restart $servername"
